apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: valkey-helmrelease
  namespace: ${releaseNamespace}
spec:
  interval: 6h
  path: ./clusters/kommander_host-cluster/apps/kommander
  postBuild:
    substitute:
      releaseNamespace: ${releaseNamespace}
      workspaceNamespace: ${workspaceNamespace}
      projectNamespace: ${projectNamespace}
  prune: true
  dependsOn:
    - name: valkey-helmrelease
  retryInterval: 1m
  sourceRef:
    kind: OCIRepository
    name: ${TEMPLATE_appName_appVersion} # substituted during build time.
    namespace: ${releaseNamespace}
  timeout: 1m
  wait: true
