apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: redis
  namespace: ${releaseNamespace}
spec:
  url: oci://registry-1.docker.io/bitnamicharts/redis
  interval: 1m
  ref:
    tag: 20.11.4
