apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: prometheus
    namespace: ${releaseNamespace}
  interval: 5m